version: '3.8'
services:
  alpaca-monitor:
    build: .
    ports:
      - "2112:2112"
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
    